### ISSUE TITLE
Support Flutter 3.10.0 when using flutter_localizations package from SDK

### ISSUE THREAD

**Issue by onlyamessenger** [zubairehman/Flogs#87]
The flutter_localizations package from the Flutter SDK itself, uses intl version 0.18.0. Flogs depends on intl version **^0.17.0**. This causes pub dependency conflicts.

Example pubspec.yaml:

```yaml
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flogs: ^2.0.1
```

Output of flutter pub get: 

`Because your_app depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because your_app depends on intl ^0.17.0, version solving failed.`
